# config file of out projext
root_path: A:\\Kaggle\\PetFinder
image_size: 224
transform: default_transforms
train_loader:
  batch_size: 64
  shuffle: True
  num_workers: 4
  pin_memory: True
  drop_last: True
val_loader:
  batch_size: 64
  shuffle: False
  num_workers: 4
  pin_memory: False
  drop_last: False
model:
  name: swin_tiny_patch4_window7_224
  output_dim: 1